### ISSUE TITLE
Not work on latest version of piwik

### ISSUE THREAD

**Issue by vdeville** [apapillon/piwik-freemobilesmsprovider-plugin#2]
Hello,
The settings is not save on last version of piwik.

**Comment by apapillon** [comment]
On Piwik 3.0.2, Mobile Messaging API changed. I just adapt this plugin to new Mobile Messaging interface. I don't have any time before.

**Comment by apapillon** [comment]
The new release are in the marketplace, you just need to update the plugin and check it works fine.
